package com.crossover.techtrial.service;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.LongSummaryStatistics;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.util.Streamable;
import org.springframework.stereotype.Service;

import com.crossover.techtrial.dto.DailyElectricity;
import com.crossover.techtrial.model.HourlyElectricity;
import com.crossover.techtrial.repository.HourlyElectricityRepository;

/**
 * HourlyElectricityServiceImpl will handle electricity generated by a Panel.
 *
 * @author Crossover
 *
 */

@Service
public class HourlyElectricityServiceImpl implements HourlyElectricityService {
	@Autowired
	HourlyElectricityRepository hourlyElectricityRepository;

	public HourlyElectricity save(HourlyElectricity hourlyElectricity) {
		return hourlyElectricityRepository.save(hourlyElectricity);
	}

	public Page<HourlyElectricity> getAllHourlyElectricityByPanelId(Long panelId, Pageable pageable) {
		return hourlyElectricityRepository.findAllByPanelIdOrderByReadingAtDesc(panelId, pageable);
	}

	public List<LongSummaryStatistics> getDaylyElectricityByPanelId(Long panelId, Pageable pageable, int dayFrom,
			int dayTo, int year) {
		Page<HourlyElectricity> page = hourlyElectricityRepository.findAllByPanelIdOrderByReadingAtDesc(panelId,
				pageable);

		List<LongSummaryStatistics> listStat = new ArrayList<LongSummaryStatistics>();
		for (int i = dayFrom; i < dayTo; i++) {

			int day = i;
			Streamable<HourlyElectricity> dataFiltered = page
					.filter(h -> h.getReadingAt().getDayOfYear() == day && h.getReadingAt().getYear() == year );

			Iterator<HourlyElectricity> it1 = dataFiltered.iterator();
			List<HourlyElectricity> list = new ArrayList<HourlyElectricity>();
			while (it1.hasNext()) {
				list.add(it1.next());
			}

			listStat.add(list.stream().mapToLong(x -> x.getGeneratedElectricity()).summaryStatistics());

		}

		return listStat;
	}

}